//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoja10.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelColecArt
    {
        public int Id { get; set; }
        public Nullable<int> id_Colecciones { get; set; }
        public Nullable<int> id_Articulo { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Colecciones Colecciones { get; set; }
    }
}
